"""
Calculate accuracy metrics from evaluation results JSONL file.

This script computes accuracy from results generated by evaluation scripts
like scripts/spatial/eval_spatial_rgpt.py or evaluate_blink.py.

Usage:
    python scripts/calc_accuracy.py --results outputs/spatial_rgpt_gemma_results.jsonl

Example output:
    Total: 100
    Correct: 85
    Skipped: 0
    Accuracy: 0.8500 (85.00%)
"""

import argparse
import sys

from theworld.evaluation import calculate_accuracy


def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(description="Calculate accuracy metrics from evaluation results JSONL")
    parser.add_argument(
        "--results",
        type=str,
        required=True,
        help="Path to results JSONL file",
    )
    return parser.parse_args()


def main():
    """Main entry point."""
    args = parse_args()

    print(f"Calculating accuracy from: {args.results}")
    print("=" * 60)

    try:
        metrics = calculate_accuracy(args.results)
    except FileNotFoundError as e:
        print(f"Error: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"Error calculating accuracy: {e}")
        sys.exit(1)

    # Print results
    print(f"\nResults:")
    print(f"  Total: {metrics['total']}")
    print(f"  Correct: {metrics['correct']}")
    print(f"  Skipped: {metrics['skipped']}")
    print(f"  Accuracy: {metrics['accuracy']:.4f} ({metrics['accuracy']*100:.2f}%)")
    print("=" * 60)


if __name__ == "__main__":
    main()
